on:
  workflow_dispatch:
    inputs:
      runner-type:
        required: true
        type: choice
        options:
          - general-cpu
          - gpu

env:
  REGISTRY: ezcoompoc
  IMAGE_NAME: test
  STORAGE_NAME: githubsa4poc
  STORAGE_CONTAINER_NAME: test
  DOWNLOAD_FILENAME: test.txt
  BUILDX_CACHE_DIR: /tmp/buildx_cache_dir/
  CONTAINER_NAME: my-container

jobs:
  job-01-ci:
    runs-on: [self-hosted, "${{ inputs.runner-type }}"]
    steps: 
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2-1. Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.11.7'

      - name: 2-2. Install Requirements and PyTest
        run: |
          pip install -r requirements.txt
          pytest app/test_rest.py | tee ${{ github.workspace}}/pytest-results-${{ github.sha }}.txt